export let actions = {
    ADD_MESSAGE: "ADD_MESSAGE",
    CHANGE_MESSAGE_TEXT: "CHANGE_MESSAGE_TEXT",
    ADD_POST: "ADD_POST",
    CHANGE_POST_TEXT: "CHANGE_POST_TEXT",
    FOLLOW: "FOLLOW",
    UNFOLLOW: "UNFOLLOW",
    SET_USERS: "SET_USERS",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SET_TOTAL_USERS_COUNT: "SET_TOTAL_USERS_COUNT",
    SET_FETCHING: "SET_FETCHING",
    SET_USER_PROFILE: "SET_USER_PROFILE",
}
